services:
  # 1. ส่วนของ Web Server
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: it-helpdesk-web
    ports:
      - "9092:80"
    volumes:
      - ./src:/var/www/html