services:
  # 1. ส่วนของ Web Server
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: it-helpdesk-web
    ports:
      - "9092:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - my-network

  # 2. ส่วนของ Database
  db:
    image: mysql:8.0
    container_name: it-helpdesk-db
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: helpdesk_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: helpdesk
      MYSQL_PASSWORD: helpdesk1234
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3309:3306"
    networks:
      - my-network

  # 3. ส่วนของ phpMyAdmin (จัดการฐานข้อมูล)
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: it-helpdesk-phpmyadmin
    ports:
      - "9093:80"
    environment:
      PMA_HOST: db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  db_data: